CREATE USER 'erp'@'localhost' IDENTIFIED BY 'senac';    
GRANT ALL PRIVILEGES ON * . * TO 'erp'@'localhost';
DROP DATABASE erp;
CREATE DATABASE erp;
USE erp;
    
CREATE TABLE tbVendors(
id INT NOT NULL AUTO_INCREMENT,
razaosocial VARCHAR(100) NOT NULL DEFAULT '',
cnpj varchar(20) NOT NULL DEFAULT '',
nomefantasia VARCHAR(100) NOT NULL DEFAULT '',
website VARCHAR(60) NOT NULL DEFAULT '',
industrysector VARCHAR(60) NOT NULL DEFAULT '',
phone1 VARCHAR(60) NOT NULL DEFAULT '',
phone2 VARCHAR(60) DEFAULT '',
contato VARCHAR(60) NOT NULL DEFAULT '',
cargo VARCHAR(60) NOT NULL DEFAULT '',
email VARCHAR(60) NOT NULL DEFAULT '',
createdby VARCHAR(60) NOT NULL DEFAULT '',
datacadastro VARCHAR(20) NOT NULL DEFAULT '',
PRIMARY KEY (id));


CREATE TABLE tbProduto(
id INT NOT NULL AUTO_INCREMENT,
nomeprod VARCHAR(100) NOT NULL DEFAULT '',
codfab varchar(60) NOT NULL DEFAULT '',
codint VARCHAR(60) NOT NULL DEFAULT '',
situacao BOOLEAN NOT NULL DEFAULT true,
descricao VARCHAR(300) NOT NULL DEFAULT '',
createdby VARCHAR(60) NOT NULL DEFAULT '',
datacadastro VARCHAR(60) DEFAULT '',
PRIMARY KEY (id));












